"""Add description to t_user_roles

Revision ID: 4e8a6ef00ac8
Revises: 4e1f053a1176
Create Date: 2025-08-15 11:09:12.048589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8a6ef00ac8'
down_revision: Union[str, Sequence[str], None] = '4e1f053a1176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user_right', 'description')
    op.add_column('t_user_role', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user_role', 'description')
    op.add_column('t_user_right', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
