"""Add name column to t_user_role

Revision ID: 6efa7445cbb9
Revises: 
Create Date: 2025-08-13 14:05:36.674583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6efa7445cbb9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 't_candidate', 't_user', ['user_id'], ['pk_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 't_cover_letter', 't_user', ['user_id'], ['pk_id'], ondelete='CASCADE')
    op.add_column('t_user_right', sa.Column('name', sa.String(), nullable=False))
    op.create_foreign_key(None, 't_user_session', 't_user', ['user_id'], ['pk_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_user_session', type_='foreignkey')
    op.drop_column('t_user_right', 'name')
    op.drop_constraint(None, 't_cover_letter', type_='foreignkey')
    op.drop_constraint(None, 't_candidate', type_='foreignkey')
    # ### end Alembic commands ###
