"""Add description column to t_user_role

Revision ID: 8260377a4220
Revises: 6efa7445cbb9
Create Date: 2025-08-15 10:52:31.518212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8260377a4220'
down_revision: Union[str, Sequence[str], None] = '6efa7445cbb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user_right', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user_right', 'description')
    # ### end Alembic commands ###
