"""Add ip_address column to t_user

Revision ID: 9f8d698fdf43
Revises: d1cc9227501d
Create Date: 2025-09-04 13:49:46.498431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f8d698fdf43'
down_revision: Union[str, Sequence[str], None] = 'd1cc9227501d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_forgot_password')
    op.drop_table('t_global_setting')
    op.add_column('t_user', sa.Column('ip_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'ip_address')
    op.create_table('t_global_setting',
    sa.Column('pk_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('pk_id', name=op.f('t_global_setting_pkey')),
    sa.UniqueConstraint('code', name=op.f('t_global_setting_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('t_forgot_password',
    sa.Column('pk_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expired', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('pk_id', name=op.f('t_forgot_password_pkey'))
    )
    # ### end Alembic commands ###
