"""Add description column to t_user_right

Revision ID: d1cc9227501d
Revises: 4e8a6ef00ac8
Create Date: 2025-08-15 13:39:09.117793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1cc9227501d'
down_revision: Union[str, Sequence[str], None] = '4e8a6ef00ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user_right', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user_right', 'description')
    # ### end Alembic commands ###
